DROP DATABASE IF EXISTS Loja_Tintas;
Create Database Loja_Tintas;
Use Loja_Tintas;

Create table PESSOA(
CPF VARCHAR(15) NOT NULL PRIMARY KEY,
NOME VARCHAR(100),
DATA_NASCIMENTO DATE
);

Create table FUNCIONARIO(
ID_FUNCIONARIO VARCHAR(15) PRIMARY KEY,
SALARIO_FUNCIONARIO INTEGER,
DATA_ADIMISSSAO DATE,
CARGA_HORARIA INTEGER,
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES PESSOA (CPF)
);

Create table CLIENTE(
ID_CLIENTE VARCHAR(15) PRIMARY KEY,
TELEFONE_CLIENTE VARCHAR(15),
EMAIL_CLIENTE VARCHAR(100),
FOREIGN KEY(ID_CLIENTE) REFERENCES PESSOA (CPF)
);

Create table PAGAMENTO(
ID_PAGAMENTO INTEGER NOT NULL PRIMARY KEY,
VALOR_PAGAMENTO INTEGER,
TIPO_PAGAMENTO VARCHAR(30),
DATA_PAGAMENTO DATE
);

Create table PEDIDO(
NUM_PEDIDO INTEGER NOT NULL PRIMARY KEY,
QTDE_ITENS INTEGER,
DATA_PEDIDO DATE,
ID_CLIENTE VARCHAR(15),
ID_FUNCIONARIO VARCHAR(15),
ID_PAGAMENTO INTEGER,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO),
FOREIGN KEY (ID_PAGAMENTO) REFERENCES PAGAMENTO (ID_PAGAMENTO)
);

Create table ENTREGADOR(
CPF_ENTREGADOR VARCHAR(15) NOT NULL PRIMARY KEY,
NOME_ENTREGADOR VARCHAR(100),
TELEFONE_ENTREGADOR VARCHAR(15)
);

Create table ENTREGA(
NUM_ENTREGA INTEGER NOT NULL PRIMARY KEY,
ENTREGADOR_RESPONSAVEL VARCHAR(100),
DATA_ENTREGA DATE,
NUM_PEDIDO INTEGER UNIQUE,
CPF_ENTREGADOR VARCHAR(15),
FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO (NUM_PEDIDO),
FOREIGN KEY (CPF_ENTREGADOR) REFERENCES ENTREGADOR (CPF_ENTREGADOR)
);

Create table FORNECEDOR(
ID_FORNECEDOR INTEGER NOT NULL PRIMARY KEY,
MARCA_REPRESENTANTE VARCHAR(50),
TELEFONE_FORNECEDOR VARCHAR(15)
);

Create table LOTE(
ID_LOTE INTEGER NOT NULL PRIMARY KEY,
QTDE_LOTE INTEGER,
DATA_VALIDADE_LOTE DATE
);

Create table TINTA(
ID_TINTA INTEGER NOT NULL PRIMARY KEY,
MARCA_TINTA VARCHAR(50),
COR_TINTA VARCHAR(30),
TIPO_TINTA VARCHAR(20),
ID_LOTE INTEGER,
FOREIGN KEY (ID_LOTE) REFERENCES LOTE (ID_LOTE)
);

Create table PEDIDO_TINTA(
NUM_PEDIDO INTEGER,
ID_TINTA INTEGER,
FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO (NUM_PEDIDO),
FOREIGN KEY (ID_TINTA) REFERENCES TINTA (ID_TINTA),
PRIMARY KEY (NUM_PEDIDO, ID_TINTA)
);

Create table FORNECEDOR_TINTA(
ID_FORNECEDOR INTEGER,
ID_TINTA INTEGER,
FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (ID_FORNECEDOR),
FOREIGN KEY (ID_TINTA) REFERENCES TINTA (ID_TINTA),
PRIMARY KEY (ID_FORNECEDOR, ID_TINTA)
);
